services:
  - type: web
    name: beadcraft
    runtime: python
    buildCommand: pip install -r requirements.txt && cargo build --manifest-path backend-rs/Cargo.toml --release
    startCommand: ./backend-rs/target/release/beadcraft-server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHON_EXECUTABLE
        value: python
