#!/usr/bin/env python3
"""
Generate Chinese character pixel data for ESP32 display.
Outputs a C++ header file with pixel arrays for Chinese text.
"""

from PIL import Image, ImageDraw, ImageFont
import os

# Characters to generate
WELCOME_TEXT = "像素豆绘"
UPLOAD_TEXT = "上传图像"

# Output directory
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER_FILE = os.path.join(OUTPUT_DIR, "..", "lib", "beadcraft-receiver", "ChinesePixels.h")

# Display settings
CHAR_WIDTH = 16
CHAR_HEIGHT = 16
FONT_SIZE = 14

def get_font():
    """Try to find a Chinese font on the system."""
    font_paths = [
        # Windows
        "C:/Windows/Fonts/msyh.ttc",  # Microsoft YaHei
        "C:/Windows/Fonts/simhei.ttf",  # SimHei
        "C:/Windows/Fonts/simsun.ttc",  # SimSun
        # Linux
        "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
        "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf",
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        # macOS
        "/System/Library/Fonts/PingFang.ttc",
        "/Library/Fonts/Arial Unicode.ttf",
    ]
    
    for path in font_paths:
        if os.path.exists(path):
            return ImageFont.truetype(path, FONT_SIZE)
    
    # Fallback to default
    print("Warning: No Chinese font found, using default")
    return ImageFont.load_default()


def char_to_pixels(char, font):
    """Convert a single character to a 2D pixel array."""
    # Create image with white background
    img = Image.new('L', (CHAR_WIDTH, CHAR_HEIGHT), color=255)
    draw = ImageDraw.Draw(img)
    
    # Draw character centered
    bbox = draw.textbbox((0, 0), char, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    
    x = (CHAR_WIDTH - text_width) // 2 - bbox[0]
    y = (CHAR_HEIGHT - text_height) // 2 - bbox[1]
    
    draw.text((x, y), char, font=font, fill=0)
    
    # Convert to binary array (1 = pixel, 0 = background)
    # Store as 16-bit values for 16-pixel width
    pixels = []
    for py in range(CHAR_HEIGHT):
        row = 0
        for px in range(CHAR_WIDTH):
            if img.getpixel((px, py)) < 128:  # Dark pixel = character
                row |= (1 << (CHAR_WIDTH - 1 - px))
        pixels.append(row)
    
    return pixels


def generate_header(text_name, chars, font):
    """Generate C++ code for a set of characters."""
    lines = []
    lines.append(f"// {text_name}")
    lines.append(f"const uint8_t {text_name}_CHARS = {len(chars)};")
    lines.append(f"const uint16_t {text_name}[{len(chars)}][{CHAR_HEIGHT}] = {{")
    
    for i, char in enumerate(chars):
        pixels = char_to_pixels(char, font)
        hex_values = ", ".join(f"0x{row:04X}" for row in pixels)
        comment = f"  // {char}"
        if i < len(chars) - 1:
            lines.append(f"    {{ {hex_values} }},{comment}")
        else:
            lines.append(f"    {{ {hex_values} }}{comment}")
    
    lines.append("};")
    return "\n".join(lines)


def main():
    print("Generating Chinese pixel data...")
    
    font = get_font()
    
    # Generate header file
    content = []
    content.append("/**")
    content.append(" * @file ChinesePixels.h")
    content.append(" * @brief Pre-generated Chinese character pixel data for 64x64 LED matrix.")
    content.append(" * ")
    content.append(" * Generated by generate_chinese_pixels.py")
    content.append(" * Character size: 16x16 pixels")
    content.append(" */")
    content.append("")
    content.append("#pragma once")
    content.append("")
    content.append("#include <Arduino.h>")
    content.append("")
    content.append(f"// Character dimensions")
    content.append(f"const uint8_t CHAR_W = {CHAR_WIDTH};")
    content.append(f"const uint8_t CHAR_H = {CHAR_HEIGHT};")
    content.append("")
    
    # Generate welcome text
    content.append(generate_header("WELCOME", WELCOME_TEXT, font))
    content.append("")
    
    # Generate upload text
    content.append(generate_header("UPLOAD", UPLOAD_TEXT, font))
    content.append("")
    
    # Write header file
    os.makedirs(os.path.dirname(HEADER_FILE), exist_ok=True)
    with open(HEADER_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(content))
    
    print(f"Generated: {HEADER_FILE}")
    print(f"  Welcome text: {WELCOME_TEXT}")
    print(f"  Upload text: {UPLOAD_TEXT}")


if __name__ == "__main__":
    main()
